from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List

UI_CAMERA_LABELS = (
    "confirmed_camera_local",
    "likely_camera_cloud",
    "possible_stream_device",
    "camera_capable_network",
    "non_camera_static_device",
    "ignore_broadcast_multicast",
)

IGNORE_MAC_PREFIXES = (
    "ff:ff:ff:ff:ff:ff",
    "33:33:",
    "01:00:5e:",
    "01:80:c2:",
)

NEGATIVE_VENDOR_BIAS = (
    "intel",
    "wnc",
    "liteon",
    "azurewave",
)

NON_CAMERA_SIBLING_HINTS = {
    "tp-link": ("archer", "deco", "re", "mesh", "extender", "router", "ax", "be", "cpe"),
    "tplink": ("archer", "deco", "re", "mesh", "extender", "router", "ax", "be", "cpe"),
    "amazon": ("echo", "kindle", "fire tv", "firetv", "alexa"),
    "ring": ("chime", "bridge", "alarm", "base station"),
    "google": ("chromecast", "google tv", "nest hub", "nest wifi"),
    "nest": ("nest hub", "nest wifi"),
    "reolink": ("nvr", "hub", "home hub"),
    "sercomm": ("router", "gateway", "mesh", "extender", "cpe", "ap"),
    "arcadyan": ("router", "gateway", "mesh", "extender", "cpe", "ap"),
    "netgear": ("orbi", "router", "extender", "nighthawk"),
    "hikvision": ("nvr", "dvr", "door station", "intercom"),
    "dahua": ("nvr", "dvr", "doorbell hub", "gateway"),
    "eufy": ("homebase", "bridge", "hub"),
    "anker": ("homebase", "bridge", "hub"),
    "wyze": ("base station", "bridge", "mesh"),
    "ubiquiti": ("udm", "dream machine", "gateway", "switch", "ap"),
    "unifi": ("udm", "dream machine", "gateway", "switch", "ap"),
    "aqara": ("hub", "bridge", "matter", "zigbee"),
    "d-link": ("router", "gateway", "mesh", "extender"),
    "dlink": ("router", "gateway", "mesh", "extender"),
    "hik-connect": ("nvr", "dvr", "door station", "intercom"),
}

CAMERA_VENDOR_BUCKETS = {
    "camera_vendor_high_confidence": (
        "netatmo",
        "ezviz",
        "hikvision",
        "reolink",
        "arlo",
        "ring",
        "google nest",
        "nest",
        "imou",
        "dahua",
        "axis",
        "hanwha",
        "bosch",
        "vivotek",
        "mobotix",
        "uniview",
        "wisenet",
    ),
    "camera_vendor_conditional": (
        "tp-link",
        "tplink",
        "tapo",
        "xiaomi",
        "imilab",
        "mijia",
        "eufy",
        "wyze",
        "ubiquiti",
        "unifi",
    ),
    "camera_vendor_generic_low_confidence": (
        "intel",
        "liteon",
        "azurewave",
        "wnc",
        "foxconn",
        "espressif",
        "realtek",
        "beken",
    ),
}

CAMERA_SIGNATURE_DATABASE: List[Dict[str, Any]] = [
    {
        "family": "tp_link_tapo",
        "brands": ["TP-Link", "Tapo", "Kasa"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "hybrid",
        "confidence_bias": 12,
        "oui_keywords": ["tp-link", "tplink", "tp-link systems"],
        "hostname_keywords": ["tapo", "kasa", "c200", "c210", "c220", "c225", "c310", "c320", "c500", "tc60", "tc65", "tc70", "tc71", "tc73", "tc74"],
        "ssid_keywords": ["tapo", "tp-link"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "ipcamera", "tapo"],
        "tls_sni_keywords": ["tapo", "tplinkcloud", "tp-link", "nbu.iot"],
        "cert_keywords": ["tp-link", "tapo"],
        "http_probe_keywords": ["tapo", "tp-link", "tplink", "onvif", "profile s", "network camera"],
        "http_server_keywords": ["goahead", "tp-link", "tapo"],
        "http_auth_keywords": ["basic realm", "digest realm", "tapo"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "profile s", "device_service", "tapo"],
        "rtsp_server_keywords": ["tp-link", "tapo", "rtsp", "network camera"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": "conditional", "other": ["vlc", "nvr"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Most wired Tapo cameras support RTSP/ONVIF; many battery models and some doorbells do not.",
    },
    {
        "family": "reolink",
        "brands": ["Reolink"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "hybrid",
        "confidence_bias": 14,
        "oui_keywords": ["reolink"],
        "hostname_keywords": ["reolink", "e1", "lumu", "lumus", "trackmix", "rlc"],
        "ssid_keywords": ["reolink"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "reolink"],
        "tls_sni_keywords": ["reolink"],
        "cert_keywords": ["reolink"],
        "http_probe_keywords": ["reolink", "network camera", "cgi", "onvif", "preview_01", "deviceinfo"],
        "http_server_keywords": ["reolink", "uc-httpd", "goahead"],
        "http_auth_keywords": ["digest realm", "reolink"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "device_service", "reolink"],
        "rtsp_server_keywords": ["reolink", "preview_01", "rtsp"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": "conditional", "other": ["cgi"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Broad RTSP/ONVIF support on many models; standalone battery models are more limited.",
    },
    {
        "family": "ezviz_hikvision_consumer",
        "brands": ["EZVIZ", "Hikvision Consumer"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "high",
        "detection_class": "hybrid",
        "confidence_bias": 13,
        "oui_keywords": ["ezviz", "hikvision"],
        "hostname_keywords": ["ezviz", "c6n", "h6c", "ty1", "cp1", "h8", "c8w", "ipc"],
        "ssid_keywords": ["ezviz"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "ipcamera"],
        "tls_sni_keywords": ["ezviz", "hik-connect", "hikvision"],
        "cert_keywords": ["ezviz", "hikvision"],
        "http_probe_keywords": ["ezviz", "hikvision", "isapi", "hik-connect", "network camera"],
        "http_server_keywords": ["hikvision", "ezviz"],
        "http_auth_keywords": ["digest realm", "hikvision", "ezviz"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "hikvision", "ezviz"],
        "rtsp_server_keywords": ["hikvision", "ezviz", "rtsp"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": "conditional", "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Model-specific ONVIF support; some door products are cloud-centric.",
    },
    {
        "family": "hikvision_enterprise",
        "brands": ["Hikvision", "Hik-Connect"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "high",
        "detection_class": "local_open",
        "confidence_bias": 18,
        "oui_keywords": ["hikvision"],
        "hostname_keywords": ["hikvision", "ds-2cd", "ds-2de", "ds-2cv", "isapi", "hik-connect"],
        "ssid_keywords": ["hikvision"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "ipcamera", "hikvision"],
        "tls_sni_keywords": ["hik-connect", "hikvision"],
        "cert_keywords": ["hikvision"],
        "http_probe_keywords": ["hikvision", "isapi", "network camera", "webs", "hik-connect"],
        "http_server_keywords": ["hikvision", "webs"],
        "http_auth_keywords": ["digest realm", "hikvision", "isapi"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "hikvision", "device_service"],
        "rtsp_server_keywords": ["hikvision", "rtsp"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": ["isapi"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Hikvision commercial network cameras commonly expose ONVIF Profile S/G, ISAPI, and RTSP.",
    },
    {
        "family": "hilook_hikvision_oem",
        "brands": ["HiLook", "Hikvision OEM"],
        "regions": ["EU", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 16,
        "oui_keywords": ["hilook", "hikvision"],
        "hostname_keywords": ["hilook", "ipc", "tvi", "nvr", "hikvision"],
        "ssid_keywords": ["hilook"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "ipcamera"],
        "tls_sni_keywords": ["hikvision", "hik-connect"],
        "cert_keywords": ["hilook", "hikvision"],
        "http_probe_keywords": ["hilook", "hikvision", "isapi", "network camera"],
        "http_server_keywords": ["hikvision", "webs"],
        "http_auth_keywords": ["digest realm", "hikvision"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "hikvision"],
        "rtsp_server_keywords": ["hikvision", "hilook"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": ["isapi"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "HiLook deployments often inherit Hikvision service traits and management surfaces.",
    },
    {
        "family": "dahua_imou",
        "brands": ["Dahua", "Imou", "Lechange"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "high",
        "detection_class": "hybrid",
        "confidence_bias": 12,
        "oui_keywords": ["dahua", "imou", "lechange"],
        "hostname_keywords": ["imou", "dahua", "ipc", "ranger", "cruiser"],
        "ssid_keywords": ["imou"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "dahua", "imou"],
        "tls_sni_keywords": ["imou", "dahua", "lechange"],
        "cert_keywords": ["dahua", "imou", "lechange"],
        "http_probe_keywords": ["dahua", "imou", "lechange", "magicbox", "rpc2", "network camera"],
        "http_server_keywords": ["dahua", "imou", "goahead"],
        "http_auth_keywords": ["digest realm", "dahua", "imou"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "dahua", "imou"],
        "rtsp_server_keywords": ["dahua", "imou", "lechange", "rtsp"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": "conditional", "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Likely local-capable on many models, but confirm by model family.",
    },
    {
        "family": "xiaomi_mi_imilab_mijia",
        "brands": ["Xiaomi", "Mi", "Mijia", "IMILAB"],
        "regions": ["EU", "ASIA"],
        "eu_presence": "high",
        "detection_class": "cloud_locked",
        "confidence_bias": 8,
        "oui_keywords": ["xiaomi", "mijia", "imilab", "chuangmi", "zhen shi"],
        "hostname_keywords": ["xiaomi", "miio", "mijia", "imilab", "chuangmi"],
        "ssid_keywords": ["xiaomi", "mijia", "imilab", "chuangmi"],
        "mdns_ssdp_keywords": ["miio"],
        "tls_sni_keywords": ["xiaomi", "mi", "miiot", "miio", "api.io.mi.com"],
        "cert_keywords": ["xiaomi"],
        "http_probe_keywords": ["xiaomi", "mijia", "imilab", "miio", "mi home"],
        "http_server_keywords": ["miio", "xiaomi"],
        "http_auth_keywords": ["xiaomi", "miio"],
        "onvif_keywords": ["xiaomi", "mijia", "imilab"],
        "rtsp_server_keywords": ["xiaomi", "mijia", "imilab"],
        "local_protocols": {"rtsp": "conditional", "onvif": False, "http_https": "conditional", "other": ["mi home cloud"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Cloud-centric family; do not rely on RTSP/ONVIF.",
    },
    {
        "family": "tuya_smart_life_oem",
        "brands": ["Tuya", "Smart Life", "generic OEM"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "cloud_locked",
        "confidence_bias": 10,
        "oui_keywords": ["tuya", "smart life"],
        "hostname_keywords": ["tuya", "ipc", "smartlife", "cloudcam", "camera"],
        "ssid_keywords": ["smartlife", "tuya"],
        "mdns_ssdp_keywords": ["ipc", "smartlife"],
        "tls_sni_keywords": ["tuya", "tuyaeu", "iot", "ipc", "a1.tuyaeu.com", "m1.tuyaeu.com"],
        "cert_keywords": ["tuya"],
        "http_probe_keywords": ["tuya", "smart life", "ipc", "camera", "tuyaeu"],
        "http_server_keywords": ["tuya", "ipc"],
        "http_auth_keywords": ["tuya", "smartlife"],
        "onvif_keywords": ["tuya", "ipc"],
        "rtsp_server_keywords": ["tuya", "ipc"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": "conditional", "other": ["proprietary tls/cloud relay"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Highest false-negative risk if detection depends on RTSP/ONVIF.",
    },
    {
        "family": "google_nest",
        "brands": ["Google Nest", "Nest"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "cloud_locked",
        "confidence_bias": 15,
        "oui_keywords": ["google", "nest"],
        "hostname_keywords": ["nest", "google"],
        "ssid_keywords": ["nest"],
        "mdns_ssdp_keywords": ["googlecast", "google"],
        "tls_sni_keywords": ["googleapis", "nest", "gvt1", "googlevideo"],
        "cert_keywords": ["google"],
        "http_probe_keywords": ["google", "nest", "webrtc", "camera", "stream"],
        "http_server_keywords": ["google", "nest"],
        "http_auth_keywords": ["google", "nest"],
        "onvif_keywords": ["google", "nest"],
        "rtsp_server_keywords": ["google", "nest"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": True, "other": ["cloud streaming"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Cloud streaming family; use upload and TLS/cloud hints.",
    },
    {
        "family": "amazon_ring",
        "brands": ["Ring", "Amazon"],
        "regions": ["EU", "US"],
        "eu_presence": "high",
        "detection_class": "cloud_locked",
        "confidence_bias": 15,
        "oui_keywords": ["ring"],
        "hostname_keywords": ["ring"],
        "ssid_keywords": ["ring"],
        "mdns_ssdp_keywords": ["ring"],
        "tls_sni_keywords": ["ring", "amazon", "aws"],
        "cert_keywords": ["amazon", "ring"],
        "http_probe_keywords": ["ring", "amazon", "camera", "doorbell"],
        "http_server_keywords": ["ring", "amazon"],
        "http_auth_keywords": ["ring", "amazon"],
        "onvif_keywords": ["ring", "amazon"],
        "rtsp_server_keywords": ["ring", "amazon"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": True, "other": ["cloud streaming", "dash"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Treat as cloud-centric streaming device.",
    },
    {
        "family": "arlo",
        "brands": ["Arlo", "Netgear"],
        "regions": ["EU", "US"],
        "eu_presence": "medium",
        "detection_class": "cloud_locked",
        "confidence_bias": 14,
        "oui_keywords": ["arlo"],
        "hostname_keywords": ["arlo"],
        "ssid_keywords": ["arlo"],
        "mdns_ssdp_keywords": ["arlo"],
        "tls_sni_keywords": ["arlo", "myarlo", "netgear", "aws"],
        "cert_keywords": ["arlo"],
        "http_probe_keywords": ["arlo", "netgear", "camera", "basestation"],
        "http_server_keywords": ["arlo", "netgear"],
        "http_auth_keywords": ["arlo", "netgear"],
        "onvif_keywords": ["arlo"],
        "rtsp_server_keywords": ["arlo"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": True, "other": ["dash"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Prefer cloud-signature plus sustained upload logic.",
    },
    {
        "family": "netatmo",
        "brands": ["Netatmo"],
        "regions": ["EU", "US"],
        "eu_presence": "medium",
        "detection_class": "hybrid",
        "confidence_bias": 14,
        "oui_keywords": ["netatmo"],
        "hostname_keywords": ["netatmo"],
        "ssid_keywords": ["netatmo"],
        "mdns_ssdp_keywords": ["homekit", "hap", "netatmo"],
        "tls_sni_keywords": ["netatmo"],
        "cert_keywords": ["netatmo"],
        "http_probe_keywords": ["netatmo", "homekit", "homekit secure video", "presence", "welcome"],
        "http_server_keywords": ["netatmo"],
        "http_auth_keywords": ["netatmo"],
        "onvif_keywords": ["netatmo", "homekit"],
        "rtsp_server_keywords": ["netatmo"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": "conditional", "other": ["homekit"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "medium", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "HomeKit-related local behavior can be valuable.",
    },
    {
        "family": "aqara_camera_hub",
        "brands": ["Aqara"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "medium",
        "detection_class": "cloud_locked",
        "confidence_bias": 10,
        "oui_keywords": ["aqara", "lumi"],
        "hostname_keywords": ["aqara", "camera hub g3", "g2h", "g2h pro", "g5 pro", "lumi"],
        "ssid_keywords": ["aqara"],
        "mdns_ssdp_keywords": ["homekit", "hap", "matter", "aqara"],
        "tls_sni_keywords": ["aqara", "lumi", "aqara.com"],
        "cert_keywords": ["aqara", "lumi"],
        "http_probe_keywords": ["aqara", "camera hub", "homekit", "matter"],
        "http_server_keywords": ["aqara", "lumi"],
        "http_auth_keywords": ["aqara", "lumi"],
        "onvif_keywords": ["aqara", "camera hub"],
        "rtsp_server_keywords": ["aqara", "lumi"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": True, "other": ["homekit", "matter bridge", "zigbee hub"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "medium", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Aqara camera products are often hub-capable devices; suppress as pure cameras unless camera behavior beats hub behavior.",
    },
    {
        "family": "wyze",
        "brands": ["Wyze"],
        "regions": ["US", "ASIA"],
        "eu_presence": "low",
        "detection_class": "cloud_locked",
        "confidence_bias": 12,
        "oui_keywords": ["wyze"],
        "hostname_keywords": ["wyze", "wyzecam", "pan", "cam v2", "cam v3"],
        "ssid_keywords": ["wyze"],
        "mdns_ssdp_keywords": ["wyze"],
        "tls_sni_keywords": ["wyze", "tutk", "iotc"],
        "cert_keywords": ["wyze"],
        "http_probe_keywords": ["wyze", "wyzecam", "tutk", "iotc"],
        "http_server_keywords": ["wyze"],
        "http_auth_keywords": ["wyze"],
        "onvif_keywords": ["wyze"],
        "rtsp_server_keywords": ["wyze"],
        "local_protocols": {"rtsp": "conditional", "onvif": False, "http_https": "conditional", "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Often cloud-centric; RTSP depends on model/firmware.",
    },
    {
        "family": "eufy_anker",
        "brands": ["Eufy", "Anker"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "cloud_locked",
        "confidence_bias": 12,
        "oui_keywords": ["eufy", "anker"],
        "hostname_keywords": ["eufy", "anker", "indoorcam", "solocam"],
        "ssid_keywords": ["eufy"],
        "mdns_ssdp_keywords": ["eufy", "homebase"],
        "tls_sni_keywords": ["eufylife", "anker", "security", "homebase"],
        "cert_keywords": ["eufy", "anker"],
        "http_probe_keywords": ["eufy", "anker", "homebase", "security"],
        "http_server_keywords": ["eufy", "anker"],
        "http_auth_keywords": ["eufy", "anker"],
        "onvif_keywords": ["eufy", "homebase"],
        "rtsp_server_keywords": ["eufy", "anker"],
        "local_protocols": {"rtsp": False, "onvif": False, "http_https": True, "other": ["cloud relay"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Cloud and hub-oriented family.",
    },
    {
        "family": "axis",
        "brands": ["Axis"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "local_open",
        "confidence_bias": 18,
        "oui_keywords": ["axis"],
        "hostname_keywords": ["axis"],
        "ssid_keywords": ["axis"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "axis"],
        "tls_sni_keywords": ["axis"],
        "cert_keywords": ["axis communications"],
        "http_probe_keywords": ["axis", "vapix", "axis-cgi", "network camera"],
        "http_server_keywords": ["axis", "boa"],
        "http_auth_keywords": ["axis", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "axis"],
        "rtsp_server_keywords": ["axis", "vapix"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": ["vapix"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "High-confidence commercial/industrial camera family.",
    },
    {
        "family": "hanwha_wisenet",
        "brands": ["Hanwha", "Wisenet", "Samsung Wisenet"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 18,
        "oui_keywords": ["hanwha", "wisenet", "samsung"],
        "hostname_keywords": ["wisenet", "hanwha"],
        "ssid_keywords": ["wisenet"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "wisenet"],
        "tls_sni_keywords": ["hanwha", "wisenet"],
        "cert_keywords": ["hanwha", "wisenet"],
        "http_probe_keywords": ["wisenet", "hanwha", "network camera", "onvif"],
        "http_server_keywords": ["wisenet", "hanwha"],
        "http_auth_keywords": ["wisenet", "hanwha", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "wisenet", "hanwha"],
        "rtsp_server_keywords": ["wisenet", "hanwha"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Commercial/industrial surveillance family.",
    },
    {
        "family": "bosch_security",
        "brands": ["Bosch"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 17,
        "oui_keywords": ["bosch"],
        "hostname_keywords": ["bosch"],
        "ssid_keywords": ["bosch"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "bosch"],
        "tls_sni_keywords": ["bosch"],
        "cert_keywords": ["bosch"],
        "http_probe_keywords": ["bosch", "network camera", "onvif"],
        "http_server_keywords": ["bosch"],
        "http_auth_keywords": ["bosch", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "bosch"],
        "rtsp_server_keywords": ["bosch"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Commercial security camera family.",
    },
    {
        "family": "vivotek",
        "brands": ["Vivotek"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 16,
        "oui_keywords": ["vivotek"],
        "hostname_keywords": ["vivotek"],
        "ssid_keywords": ["vivotek"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "vivotek"],
        "tls_sni_keywords": ["vivotek"],
        "cert_keywords": ["vivotek"],
        "http_probe_keywords": ["vivotek", "network camera", "onvif"],
        "http_server_keywords": ["vivotek"],
        "http_auth_keywords": ["vivotek", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "vivotek"],
        "rtsp_server_keywords": ["vivotek"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Commercial IP camera family.",
    },
    {
        "family": "uniview",
        "brands": ["Uniview", "Uniview Technologies"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 16,
        "oui_keywords": ["uniview", "unv"],
        "hostname_keywords": ["uniview", "unv"],
        "ssid_keywords": ["unv"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "uniview"],
        "tls_sni_keywords": ["uniview", "unv"],
        "cert_keywords": ["uniview"],
        "http_probe_keywords": ["uniview", "unv", "network camera", "onvif"],
        "http_server_keywords": ["uniview", "unv"],
        "http_auth_keywords": ["uniview", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "uniview", "unv"],
        "rtsp_server_keywords": ["uniview", "unv"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Commercial and municipal deployments.",
    },
    {
        "family": "mobotix",
        "brands": ["Mobotix"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 17,
        "oui_keywords": ["mobotix"],
        "hostname_keywords": ["mobotix"],
        "ssid_keywords": ["mobotix"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "mobotix"],
        "tls_sni_keywords": ["mobotix"],
        "cert_keywords": ["mobotix"],
        "http_probe_keywords": ["mobotix", "network camera", "onvif", "mxpeg"],
        "http_server_keywords": ["mobotix"],
        "http_auth_keywords": ["mobotix", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "mobotix"],
        "rtsp_server_keywords": ["mobotix", "mxpeg"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Industrial/commercial camera family.",
    },
    {
        "family": "instar",
        "brands": ["INSTAR"],
        "regions": ["EU", "ASIA"],
        "eu_presence": "medium",
        "detection_class": "local_open",
        "confidence_bias": 14,
        "oui_keywords": ["instar"],
        "hostname_keywords": ["instar", "in-8401", "in-9008", "in-9408"],
        "ssid_keywords": ["instar"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "instar"],
        "tls_sni_keywords": ["instar"],
        "cert_keywords": ["instar"],
        "http_probe_keywords": ["instar", "network camera", "onvif", "cgi"],
        "http_server_keywords": ["instar"],
        "http_auth_keywords": ["instar", "digest realm"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "instar"],
        "rtsp_server_keywords": ["instar", "rtsp"],
        "local_protocols": {"rtsp": True, "onvif": True, "http_https": True, "other": ["cgi", "mjpeg"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "EU-focused camera family with RTSP/ONVIF/HomeKit-capable Wi-Fi models.",
    },
    {
        "family": "dlink_mydlink_camera",
        "brands": ["D-Link", "mydlink"],
        "regions": ["EU", "ASIA", "US"],
        "eu_presence": "medium",
        "detection_class": "hybrid",
        "confidence_bias": 11,
        "oui_keywords": ["d-link", "dlink", "mydlink"],
        "hostname_keywords": ["dcs-", "mydlink", "d-link", "dlink"],
        "ssid_keywords": ["mydlink", "dlink"],
        "mdns_ssdp_keywords": ["onvif", "rtsp", "dlink"],
        "tls_sni_keywords": ["mydlink", "dlink"],
        "cert_keywords": ["d-link", "dlink", "mydlink"],
        "http_probe_keywords": ["d-link", "dlink", "mydlink", "network camera"],
        "http_server_keywords": ["d-link", "mydlink"],
        "http_auth_keywords": ["d-link", "mydlink"],
        "onvif_keywords": ["onvif", "networkvideotransmitter", "dlink", "mydlink"],
        "rtsp_server_keywords": ["dlink", "mydlink"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": True, "other": []},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "D-Link camera and NVR estate often exposes ONVIF-compatible workflows under mydlink and DCS model lines.",
    },
    {
        "family": "ubiquiti_unifi_protect",
        "brands": ["Ubiquiti", "UniFi Protect"],
        "regions": ["EU", "US", "ASIA"],
        "eu_presence": "high",
        "detection_class": "hybrid",
        "confidence_bias": 13,
        "oui_keywords": ["ubiquiti", "unifi"],
        "hostname_keywords": ["unifi", "protect", "g4", "g5", "uvc"],
        "ssid_keywords": ["unifi"],
        "mdns_ssdp_keywords": ["protect", "unifi", "onvif"],
        "tls_sni_keywords": ["ui.com", "ubnt", "unifi"],
        "cert_keywords": ["ubiquiti"],
        "http_probe_keywords": ["unifi", "protect", "ubiquiti", "uvc", "network camera"],
        "http_server_keywords": ["ubiquiti", "unifi"],
        "http_auth_keywords": ["ubiquiti", "unifi"],
        "onvif_keywords": ["onvif", "protect", "ubiquiti"],
        "rtsp_server_keywords": ["ubiquiti", "unifi", "protect"],
        "local_protocols": {"rtsp": "conditional", "onvif": "conditional", "http_https": True, "other": ["protect"]},
        "traffic_profile": {"static_rssi": True, "probe_rate": "low", "uplink_bias": "high", "long_lived_flows": True, "packet_shape": "steady"},
        "notes": "Common prosumer/commercial camera family.",
    },
]


def match_keywords(text: str, keywords: List[str] | tuple[str, ...]) -> List[str]:
    haystack = str(text or "").lower()
    return [keyword for keyword in keywords if keyword and keyword.lower() in haystack]


@lru_cache(maxsize=1)
def load_lab_camera_profiles() -> List[Dict[str, Any]]:
    path = Path(__file__).resolve().parents[3] / "config" / "lab_camera_profiles.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    if not isinstance(data, dict) or not bool(data.get("enabled")):
        return []
    profiles = list(data.get("profiles") or [])
    return [profile for profile in profiles if isinstance(profile, dict)]
